# Root url of oval definitions 
oval_definitions_url: https://www.redhat.com/security/data/oval/v2 
 
# Mapping of OS version to definition files 
oval_files_map:
  '9.2':
    - rhel-9.2-eus.oval.xml
    - openstack-17.1.oval.xml
    - fast-datapath.oval.xml
  '8.4':
    - rhel-8.4-tus.oval.xml
    - openstack-17.1.oval.xml.bz2
    - fast-datapath.oval.xml
  '8.2':
    - rhel-8.2-tus.oval.xml
    - openstack-16.1.oval.xml.bz2
    - fast-datapath.oval.xml

# Run CVE scan on host OS
scan_host: True

# Run CVE scan on container images downloaded by root
scan_container_images: False

# Create tarball with all html reports
compress_report: True

# Temporary directory to use in rhosp nodes and ansible host
tmp_directory_root: /tmp

# Where to rsync the tar file when finished
#target_server: <hostname>:<directory>
