# Not using ansible.posix.synchronize because it's not available in RHEL8's Ansible
- name: Copy report files to target
  run_once: True
  delegate_to: localhost
  ansible.builtin.shell:
    rsync -e "ssh -o StrictHostKeyChecking=no" -r {{ report_directory }} {{ target_server }}
  when:
    - not compress_report
    - target_server

- name: Copy report tarball to target
  run_once: True
  delegate_to: localhost
  ansible.builtin.shell:
    rsync -e "ssh -o StrictHostKeyChecking=no" {{ report_directory }}.tgz {{ target_server }}
  when:
    - compress_report
    - target_server is defined
