- name: Copy report files to target
  run_once: True
  delegate_to: localhost
  ansible.builtin.shell:
    rsync -e "ssh -o StrictHostKeyChecking=no" -r {{ report_directory }} {{ target_server }}
  when: copy_reports

- name: Copy report tarball to target
  run_once: True
  delegate_to: localhost
  ansible.builtin.shell:
    rsync -e "ssh -o StrictHostKeyChecking=no" {{ report_directory }}.tgz {{ target_server }}
  when: compress_report
