- name: Block to create report and rerport path
  run_once: True
  delegate_to: localhost
  block:
  - name: Create report archive
    ansible.builtin.shell:
      tar -cz -C {{ report_directory }} -f {{ report_directory }}.tgz .

  - name: Report path to archive
    debug:
      msg: "{{ report_directory }}.tgz"
    when: target_server is not defined
