# Not using ansible.posix.synchronize because it's not available in RHEL8's Ansible
- name: Remove oval files from target servers
  tags: never
  ansible.builtin.file:
    path: "{{ report_directory }}/{{ item }}"
    state: absent
  loop: "{{ oval_files_map[ansible_facts.distribution_version] }}"

- name: List files in target host
  ansible.builtin.shell:
    find {{ report_directory }}/{{ inventory_hostname }} -type f
  register: target_files

- name: Copy target files to ansible host
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: "{{ report_directory }}/{{ inventory_hostname }}/"
    flat: True
  loop: "{{ target_files.stdout_lines }}"
