- name: Preparation tasks
  tags:
    - preparation
    - always
  import_tasks: ./preparation.yaml
  when: scan_host or scan_container_images

- name: Scan host OS
  tags:
    - scan_host
  import_tasks: ./scan_host.yaml
  when: scan_host

- name: Scan container images
  tags:
    - scan_images
  import_tasks: ./scan_container_images.yaml
  when: scan_container_images

- name: Fetch reports from target hosts
  tags:
    - fetch_reports
  import_tasks: ./fetch_reports.yaml
  
- name: Create report tarball
  tags:
    - compress
  import_tasks: ./create_tarball.yaml
  when:
    - scan_host or scan_container_images
    - compress_report

- name: Copy reports to target server
  tags:
    - copy_target
  import_tasks: ./copy_reports.yaml
  when:
    - scan_host or scan_container_images
    - target_server is defined

- name: Cleanup temporary files
  tags:
    - cleanup
    - always
  import_tasks: ./cleanup.yaml
