- name: Gather facts subset
  tags:
    - always
  run_once: True
  ansible.builtin.setup:
    gather_subset:
      - date_time
      - distribution_version

- name: Install openscap and related utilities
  tags:
    - packages
  become: True
  ansible.builtin.dnf:
    name: 
      - openscap-scanner
      - openscap-utils
      - bzip2
    state: present

- name: Set fact with temporary report directory
  tags:
    - directory
  run_once: True
  delegate_to: localhost
  set_fact:
    report_directory: "{{ tmp_directory_root }}/oscap_report_{{ ansible_facts.date_time.iso8601_basic_short }}"

- name: "Create temporary report directory: {{ report_directory }}"
  tags:
    - directory
  ansible.builtin.file:
    state: directory
    path: "{{ report_directory }}"

- name: Create hosts directory structure
  tags:
    - directory
  ansible.builtin.file:
    state: directory
    path: "{{ report_directory }}/{{ inventory_hostname }}"

- name: Download definition files
  tags:
    - preparation
  run_once: True
  delegate_to: localhost
  become: False
  ansible.builtin.get_url:
    url: "{{ oval_definitions_url }}/RHEL{{ ansible_facts.distribution_major_version }}/{{ item }}.bz2"
    dest: "{{ tmp_directory_root }}/"
    mode: '0444'
  loop: "{{ oval_files_map[ansible_facts.distribution_version] }}"
  loop_control:
    label: "{{ tmp_directory_root }}/{{ item }}.bz2"

- name: Extract oval files
  tags:
    - preparation
  run_once: True
  delegate_to: localhost
  ansible.builtin.command:
    bunzip2 "{{ tmp_directory_root }}/{{ item }}.bz2"
  loop: "{{ oval_files_map[ansible_facts.distribution_version] }}"
  loop_control:
    label: "{{ tmp_directory_root }}/{{ item }}.bz2"

- name: Copy oval file to target servers
  tags:
    - preparation
  ansible.builtin.copy:
    src: "{{ tmp_directory_root }}/{{ item }}"
    dest: "{{ report_directory }}/"
  loop: "{{ oval_files_map[ansible_facts.distribution_version] }}"
  loop_control:
    label: "{{ report_directory }}/{{ item }}"

- name: Remove definition files from ansible host
  tags:
    - preparation
  run_once: True
  delegate_to: localhost
  ansible.builtin.file:
    path: "{{ tmp_directory_root }}/{{ item }}"
    state: absent
  loop: "{{ oval_files_map[ansible_facts.distribution_version] }}"
  loop_control:
    label: "{{ tmp_directory_root }}/{{ item }}"
