- name: List container images
  tags:
    - list_images
  become: True
  ansible.builtin.shell:
    podman images -q
  register: container_images

- name: Inspect images
  become: True
  ansible.builtin.shell:
    podman inspect {{ item }}
  loop: "{{ container_images.stdout_lines }}"
  register: podman_inspect

- name: Scan container images 
  tags:
    - scan_images
  become: True
  ansible.builtin.shell:
    oscap-podman {{ image_id }} oval eval --report {{ report_directory }}/{{ inventory_hostname }}/{{ image_report }} {{ report_directory }}/{{ item[1] }}
  vars:
    image_json: "{{ item[0].stdout | from_json }}"
    image_id: "{{ item[0].item }}"
    image_name: "{{ image_json[0].Config.Labels.name | default('noname') | split('/') | last }}"
    image_version: "{{ image_json[0].Config.Labels.version | default('noversion') }}"
    image_release: "{{ image_json[0].Config.Labels.release | default('norelease') }}"
    image_nvri: "{{ image_name }}_{{ image_version }}-{{ image_release }}_{{ image_id }}"
    image_report: "{{ image_nvri }}_{{ item[1] }}.html"
  loop: "{{ podman_inspect.results | product(oval_files_map[ansible_facts.distribution_version]) | list }}"
  loop_control:
    label: "{{ image_report }}"
  register: image_scans
