- name: Perform OpenSCAP scan
  tags:
    - scan_hosts
  become: True
  ansible.builtin.shell: 
    oscap oval eval --report {{ report_directory }}/{{ inventory_hostname }}.html {{ report_directory }}/{{ osp_oval_files_map[ansible_facts.distribution_version] }}
